version: 0.2

env:
  variables:
    CREATE_FOR_DELIVERY: "get value from cloudformation"
    DEVOPS_ACCOUNT_ID: "get value from cloudformation"
    ECR_NAME: "get value from cloudformation"
    REPOSITORY: "get value from cloudformation"
    SUFFIX: "get value from cloudformation"

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - set -e
      - echo log-in into ecr
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin ${DEVOPS_ACCOUNT_ID}.dkr.ecr.eu-central-1.amazonaws.com
  build:
    commands:
      - echo start build on `date`
      - set -e
      - ls -lah
      - mvn clean install
      - |
        if [ $CREATE_FOR_DELIVERY = "true" ]
        then
          echo "start build and push process for DELIVERY stages:"
          docker build -f src/main/docker/Dockerfile.jvm -t ${REPOSITORY}-${SUFFIX}-delivery-image:$CODEBUILD_RESOLVED_SOURCE_VERSION .

          docker tag ${REPOSITORY}-${SUFFIX}-delivery-image:$CODEBUILD_RESOLVED_SOURCE_VERSION \
          ${DEVOPS_ACCOUNT_ID}.dkr.ecr.eu-central-1.amazonaws.com/${ECR_NAME}:$CODEBUILD_RESOLVED_SOURCE_VERSION

          docker push ${DEVOPS_ACCOUNT_ID}.dkr.ecr.eu-central-1.amazonaws.com/${ECR_NAME}:$CODEBUILD_RESOLVED_SOURCE_VERSION
          printf '[{"name":"${Repository}-${Suffix}-container","imageUri":"${DEVOPS_ACCOUNT_ID}.dkr.ecr.eu-central-1.amazonaws.com/${ECR_NAME}:$CODEBUILD_RESOLVED_SOURCE_VERSION"}]' > imagedefinitions.json

        elif [ $CREATE_FOR_DELIVERY = "false" ]
        then
          echo "start build and push process for PREVIEW stage:"
          docker build -f src/main/docker/Dockerfile.jvm -t ${REPOSITORY}-${SUFFIX}-preview-image:${SUFFIX} .

          docker tag ${REPOSITORY}-${SUFFIX}-preview-image:${SUFFIX} \
          ${DEVOPS_ACCOUNT_ID}.dkr.ecr.eu-central-1.amazonaws.com/${ECR_NAME}:${SUFFIX}

          docker push ${DEVOPS_ACCOUNT_ID}.dkr.ecr.eu-central-1.amazonaws.com/${ECR_NAME}:${SUFFIX}
          printf '[{"name":"%s-%s-container","imageUri":"%s.dkr.ecr.eu-central-1.amazonaws.com/%s:%s"}]' ${Repository} ${Suffix} ${DEVOPS_ACCOUNT_ID} ${ECR_NAME} ${SUFFIX} > imagedefinitions.json

        else
          echo "!!! ERROR, invalid boolean for env-variable: CREATE_FOR_DELIVERY !!!"
        fi
artifacts:
  files:
    - imagedefinitions.json
