AWSTemplateFormatVersion: 2010-09-09
Description: The Cf-Stack for the DynamoDB-Table

Parameters:
  Project:
    Type: String
  Repository:
    Type: String
  Stage:
    Type: String
  Suffix:
    Type: String

Resources: 
  ddbTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: "partitionkey"
          AttributeType: "S"
        - AttributeName: "sortkey"
          AttributeType: "S"  

      KeySchema: 
        - AttributeName: "partitionkey"
          KeyType: "HASH"
        - AttributeName: "sortkey"
          KeyType: "RANGE"  
      ProvisionedThroughput: 
        ReadCapacityUnits: 50
        WriteCapacityUnits: 50
      TableName: !Sub "ddb-table-${Repository}-${Stage}-${Suffix}"

Outputs:
  DDBTableArnOutput:
    Description: ARN of the DynamoDbTable
    Value: !GetAtt ddbTable.Arn
    Export:
      Name: !Sub "${AWS::StackName}:arn"

